language: java

jdk:
  - oraclejdk8

env:
  - NODE_VERSION=0.12

sudo: false

branches:
  except:
    - master

before_install:
  - nvm install $NODE_VERSION
  - npm install -g grunt-cli
  - npm install -g bower
  - rvm install 2.2.0
  - gem install bundler
  - bundle install

install:
  - npm install
  - bower install

before_script:
  - nvm use $NODE_VERSION
  - grunt build:dist

script: grunt test
